\documentclass{article}

\begin{document}
\begin{center} \large
Scrachpad Notebook  \\
\end{center}

This needs the scratchpad program, which is not ready for prime time.
(or even beta testing)

>>x = 1 in    0.0254  m
>>y = 1 ft    0.3048  m
>>x * y  0.007742  m^2
>>1 dog + 1 cat  ERROR: Encountered "dog" at line 4, column 40.
Was expecting one of:
    "\bCELL_END" ...
    "(" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "^" ...
    <UNIT> ...
    "," ...
    <PLUSMINUS> ...
    "[" ...
    "\\[" ...
    
>>   dog + cat
two three

  ERROR: Encountered "two" at line 19, column 1.
Was expecting one of:
    "\bCELL_END" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "^" ...
    "," ...
    "(" ...
    "[" ...
    "\\[" ...
    
>>Cp = 1         1  


>>z  = 3 +/- 2         3+/-       2  
>>   
>>dog           0  
>>  


\end{document}
